"""RxFlow — generic, robust, functional stream-processing engine.

Domain-agnostic core. No business logic lives here. Applications are topologies
plus small callables passed at configuration time.
"""

from rxflow.clock import Clock, VirtualClock, WallClock, parse_duration
from rxflow.compose import compose, operator
from rxflow.connectors import (
    CallbackSink,
    CircuitBreaker,
    FileSink,
    FileSource,
    FullQueue,
    MemorySink,
    PartitionedLog,
    ProtectedSink,
    QueueSource,
    StdoutSink,
    WebhookSource,
)
from rxflow.context import Runtime, Subscription
from rxflow.envelope import Envelope, as_envelope
from rxflow.errors import StreamProcessingError
from rxflow.metrics import Metrics, StageMetrics
from rxflow.observable import Observable
from rxflow.operators import (
    Window,
    as_table,
    assign_trace_id,
    assign_watermarks,
    buffer_count,
    debounce,
    distinct_until_changed,
    fan_out,
    filter_op,
    flat_map,
    join_stream,
    join_table,
    key_by,
    map_op,
    map_payload,
    merge,
    sample,
    scan_op,
    session_window,
    skip,
    sliding_window,
    take,
    tap,
    throttle,
    timeout,
    tumbling_window,
    validate,
)
from rxflow.state import KeyValueStore, load_checkpoint, save_checkpoint

__all__ = [
    "CallbackSink",
    "CircuitBreaker",
    "Clock",
    "Envelope",
    "FileSink",
    "FileSource",
    "FullQueue",
    "KeyValueStore",
    "MemorySink",
    "Metrics",
    "Observable",
    "PartitionedLog",
    "ProtectedSink",
    "QueueSource",
    "Runtime",
    "StageMetrics",
    "StdoutSink",
    "StreamProcessingError",
    "Subscription",
    "VirtualClock",
    "WallClock",
    "WebhookSource",
    "Window",
    "as_envelope",
    "as_table",
    "assign_trace_id",
    "assign_watermarks",
    "buffer_count",
    "compose",
    "debounce",
    "distinct_until_changed",
    "fan_out",
    "filter_op",
    "flat_map",
    "join_stream",
    "join_table",
    "key_by",
    "load_checkpoint",
    "map_op",
    "map_payload",
    "merge",
    "operator",
    "parse_duration",
    "sample",
    "save_checkpoint",
    "scan_op",
    "session_window",
    "skip",
    "sliding_window",
    "take",
    "tap",
    "throttle",
    "timeout",
    "tumbling_window",
    "validate",
]
